[project]
name = "enterprise-olist-data-platform"
version = "0.1.0"
description = "Enterprise End-to-End Data Engineering Project using the Olist E-Commerce Dataset"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "boto3>=1.43.62",
    "dbt-core>=1.12.0",
    "dbt-snowflake>=1.12.0",
    "delta-spark==3.2.0",
    "pandas>=2.3.3",
    "pyarrow>=25.0.0",
    "pyspark==3.5.1",
    "python-dotenv>=1.2.2",
    "snowflake-connector-python>=4.7.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
